services:
  database:
    image: postgres:15
    container_name: postgres-school
    environment:
      POSTGRES_DB: school_directory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - educonnect-network
    restart: unless-stopped

  backend:
    build:
      context: ./educonnect
      dockerfile: Dockerfile
    container_name: educonnect-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-school:5432/school_directory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/schools"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - educonnect-network
    restart: unless-stopped

  frontend:
    build:
      context: ./school-directory-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: /api
    container_name: educonnect-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - educonnect-network
    restart: unless-stopped


networks:
  educonnect-network:
    driver: bridge

volumes:
  postgres_data:
